### ISSUE TITLE
Don't use Slack article does not feature the Matrix.

### ISSUE THREAD

**Issue by almereyda** [SirCmpwn/sircmpwn.github.io#3]
Since the No Slack article took its way through the various networks, another ecosystem emerged which aims at replacing most current open and propriertary messaging infrastructures. The @matrix-org ecosystem aims at bridging siloed networks into each other, to increase mixing of communities.

The article doesn't mention it yet, why I'd love to propose a Pull Request, if this blog is open for such contributions?

**Comment by SirCmpwn** [comment]
Sure. Add it to the end of the article after an \<hr /\> and credit yourself.

**Comment by SirCmpwn** [comment]
You can make a horizontal rule in markdown with \-\-\-

---
