### ISSUE TITLE
Flattr contributions

### ISSUE THREAD

**Issue by da2x** [SirCmpwn/sircmpwn.github.io#8]
Hi, please accept contributions through [Flattr](https://flattr.com/creators). You just need to link your website and GitHub account to Flattr and anyone with the Flattr browser extension who spends any time on your website/projects will contribute funding. Users pay in a monthly sum that is distributed to the websites they visit; like a monthly Patreon for the entire web. No need to include scripts or change anything on your actual website, just link up your accounts and domains.

**Comment by SirCmpwn** [comment]
I used Flattr a while ago, but I don't like the way it's designed and I was never actually able to get money *out* of it effectively. I'd rather not set this up.

**Comment by da2x** [comment]
They’ve redesigned the service to not use Flattr buttons but rather contribute automatically based on web browser history (happens on the device).

**Comment by SirCmpwn** [comment]
I'll take another look.
